### Calculate Price
POST http://127.0.0.1:8337/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "SALE15PERCENT"
}

### Execute Purchase
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "SALE10AMOUNT",
  "paymentProcessor": "paypal"
}

### Execute Unsuccessfull Purchase via "stripe"
### (StripePaymentProcessor fails when price less than 100)
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 2,
  "taxNumber": "GR123456789",
  "paymentProcessor": "stripe"
}

### Execute Unsuccessfull Purchase via "paypal"
### (PaypalPaymentProcessor fails when price more than 100000)
POST http://127.0.0.1:8337/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 4,
  "taxNumber": "GR123456789",
  "paymentProcessor": "paypal"
}
